
module "orangehrm" {
  source                           = "./orangehrm"
  tenancy_ocid                     = var.tenancy_ocid
  region                           = var.region
  compartment_ocid                 = var.compartment_ocid
  availability_domain_name         = var.availability_domain_name
  vm_display_name                  = var.vm_display_name
  vm_compute_shape                 = var.vm_compute_shape
  vm_flex_shape_ocpus              = var.vm_flex_shape_ocpus
  vm_flex_shape_memory             = var.vm_flex_shape_memory
  ssh_authorized_keys              = var.ssh_public_key
  vcn_display_name                 = var.vcn_display_name
  vcn_cidr_block                   = var.vcn_cidr_block
  vcn_dns_label                    = var.vcn_dns_label
  subnet_id                        = var.subnet_id
  subnet_display_name              = var.subnet_display_name
  subnet_cidr_block                = var.subnet_cidr_block
  subnet_dns_label                 = var.subnet_dns_label
  orangehrm_admin_user_name        = var.orangehrm_admin_user_name
  orangehrm_admin_user_password    = var.orangehrm_admin_user_password
  orangehrm_admin_email            = var.orangehrm_admin_email
  orangehrm_admin_firstname        = var.orangehrm_admin_firstname
  orangehrm_admin_lastname         = var.orangehrm_admin_lastname
  orangehrm_admin_contact_number   = var.orangehrm_admin_contact_number
  organization_name                = var.instance_organization_name
  registration_consent             = var.registration_consent
  mysql_root_user_password         = "admin@Admin123"
  orangehrm_database_user_password = "admin@Admin123"
  mysql_hostname                   = "mysql"
}
