# https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/terraformconfigresourcemanager_topic-schema.htm

title: Deploy OrangeHRM Starter on OCI with MDS
description: Deploy OrangeHRM Starter (Open Source) on OCI with MySQL Database Service
schemaVersion: 1.1.0
version: "20230127"

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - vm_user
      - availability_domain_number

  # - title: "OrangeHRM: License Acceptance"
  #   variables:
  #     - license_acceptance

  - title: "OrangeHRM: Instance Creation"
    variables:
      - instance_organization_name
      - instance_country

  - title: "OrangeHRM: Admin User Creation"
    variables:
      - orangehrm_admin_firstname
      - orangehrm_admin_lastname
      - orangehrm_admin_email
      - orangehrm_admin_contact_number
      - orangehrm_admin_user_name
      - orangehrm_admin_user_password
      - registration_consent

  - title: "Compute Configuration"
    variables:
      - compartment_ocid
      - vm_display_name
      - vm_compute_shape
      - vm_flex_shape_ocpus
      - vm_flex_shape_memory
      - availability_domain_name
      - ssh_public_key

  - title: "Virtual Cloud Network Configuration"
    variables:
      - vcn_display_name
      - vcn_dns_label
      - vcn_cidr_block

  - title: "Subnet Configuration"
    visible: true
    variables:
      - subnet_display_name
      - subnet_dns_label
      - subnet_cidr_block

  - title: "MySQL Database Configuration"
    visible: true
    variables:
      - privileged_database_username
      - privileged_database_user_password
      - database_name
      - orangehrm_database_user_password
      - database_hostname
      - mysql_shape

  - title: "Additional Configuration Options"
    variables:
      - tag_key_name
      - tag_value

variables:
  ######################################################
  ##############    HIDDEN VARIABLES       #############
  ######################################################

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  ######################################################
  #########    OrangeHRM: License Acceptance      ######
  ######################################################

  # license_acceptance:
  #   type: boolean
  #   required: true
  #   title: License Acceptance
  #   description: I accept the terms in the [License Agreement](https://github.com/orangehrm/orangehrm/blob/main/LICENSE)
  #   default: true
  #   disable: true

  ######################################################
  #########    OrangeHRM: Instance Creation      #######
  ######################################################

  instance_organization_name:
    type: string
    required: true
    title: Organization Name

  instance_country:
    type: enum
    required: true
    title: Country
    enum:
      - "Andorra"
      - "United Arab Emirates"
      - "Afghanistan"
      - "Antigua and Barbuda"
      - "Anguilla"
      - "Albania"
      - "Armenia"
      - "Netherlands Antilles"
      - "Angola"
      - "Antarctica"
      - "Argentina"
      - "American Samoa"
      - "Austria"
      - "Australia"
      - "Aruba"
      - "Azerbaijan"
      - "Bosnia and Herzegovina"
      - "Barbados"
      - "Bangladesh"
      - "Belgium"
      - "Burkina Faso"
      - "Bulgaria"
      - "Bahrain"
      - "Burundi"
      - "Benin"
      - "Bermuda"
      - "Brunei Darussalam"
      - "Bolivia"
      - "Brazil"
      - "Bahamas"
      - "Bhutan"
      - "Bouvet Island"
      - "Botswana"
      - "Belarus"
      - "Belize"
      - "Canada"
      - "Cocos (Keeling) Islands"
      - "Congo, the Democratic Republic of the"
      - "Central African Republic"
      - "Congo"
      - "Switzerland"
      - "Cote D'Ivoire"
      - "Cook Islands"
      - "Chile"
      - "Cameroon"
      - "China"
      - "Colombia"
      - "Costa Rica"
      - "Serbia and Montenegro"
      - "Cuba"
      - "Cape Verde"
      - "Christmas Island"
      - "Cyprus"
      - "Czech Republic"
      - "Germany"
      - "Djibouti"
      - "Denmark"
      - "Dominica"
      - "Dominican Republic"
      - "Algeria"
      - "Ecuador"
      - "Estonia"
      - "Egypt"
      - "Western Sahara"
      - "Eritrea"
      - "Spain"
      - "Ethiopia"
      - "Finland"
      - "Fiji"
      - "Falkland Islands (Malvinas)"
      - "Micronesia, Federated States of"
      - "Faroe Islands"
      - "France"
      - "Gabon"
      - "United Kingdom"
      - "Grenada"
      - "Georgia"
      - "French Guiana"
      - "Ghana"
      - "Gibraltar"
      - "Greenland"
      - "Gambia"
      - "Guinea"
      - "Guadeloupe"
      - "Equatorial Guinea"
      - "Greece"
      - "South Georgia and the South Sandwich Islands"
      - "Guatemala"
      - "Guam"
      - "Guinea-Bissau"
      - "Guyana"
      - "Hong Kong"
      - "Heard Island and Mcdonald Islands"
      - "Honduras"
      - "Croatia"
      - "Haiti"
      - "Hungary"
      - "Indonesia"
      - "Ireland"
      - "Israel"
      - "India"
      - "British Indian Ocean Territory"
      - "Iraq"
      - "Iran, Islamic Republic of"
      - "Iceland"
      - "Italy"
      - "Jamaica"
      - "Jordan"
      - "Japan"
      - "Kenya"
      - "Kyrgyzstan"
      - "Cambodia"
      - "Kiribati"
      - "Comoros"
      - "Saint Kitts and Nevis"
      - "Korea, Democratic People's Republic of"
      - "Korea, Republic of"
      - "Kuwait"
      - "Cayman Islands"
      - "Kazakhstan"
      - "Lao People's Democratic Republic"
      - "Lebanon"
      - "Saint Lucia"
      - "Liechtenstein"
      - "Sri Lanka"
      - "Liberia"
      - "Lesotho"
      - "Lithuania"
      - "Luxembourg"
      - "Latvia"
      - "Libyan Arab Jamahiriya"
      - "Morocco"
      - "Monaco"
      - "Moldova, Republic of"
      - "Madagascar"
      - "Marshall Islands"
      - "Macedonia, the Former Yugoslav Republic of"
      - "Mali"
      - "Myanmar"
      - "Mongolia"
      - "Macao"
      - "Northern Mariana Islands"
      - "Martinique"
      - "Mauritania"
      - "Montserrat"
      - "Malta"
      - "Mauritius"
      - "Maldives"
      - "Malawi"
      - "Mexico"
      - "Malaysia"
      - "Mozambique"
      - "Namibia"
      - "New Caledonia"
      - "Niger"
      - "Norfolk Island"
      - "Nigeria"
      - "Nicaragua"
      - "Netherlands"
      - "Norway"
      - "Nepal"
      - "Nauru"
      - "Niue"
      - "New Zealand"
      - "Oman"
      - "Panama"
      - "Peru"
      - "French Polynesia"
      - "Papua New Guinea"
      - "Philippines"
      - "Pakistan"
      - "Poland"
      - "Saint Pierre and Miquelon"
      - "Pitcairn"
      - "Puerto Rico"
      - "Palestinian Territory, Occupied"
      - "Portugal"
      - "Palau"
      - "Paraguay"
      - "Qatar"
      - "Reunion"
      - "Romania"
      - "Russian Federation"
      - "Rwanda"
      - "Saudi Arabia"
      - "Solomon Islands"
      - "Seychelles"
      - "Sudan"
      - "Sweden"
      - "Singapore"
      - "Saint Helena"
      - "Slovenia"
      - "Svalbard and Jan Mayen"
      - "Slovakia"
      - "Sierra Leone"
      - "San Marino"
      - "Senegal"
      - "Somalia"
      - "Suriname"
      - "Sao Tome and Principe"
      - "El Salvador"
      - "Syrian Arab Republic"
      - "Swaziland"
      - "Turks and Caicos Islands"
      - "Chad"
      - "French Southern Territories"
      - "Togo"
      - "Thailand"
      - "Tajikistan"
      - "Tokelau"
      - "Timor-Leste"
      - "Turkmenistan"
      - "Tunisia"
      - "Tonga"
      - "Turkey"
      - "Trinidad and Tobago"
      - "Tuvalu"
      - "Taiwan"
      - "Tanzania, United Republic of"
      - "Ukraine"
      - "Uganda"
      - "United States Minor Outlying Islands"
      - "United States"
      - "Uruguay"
      - "Uzbekistan"
      - "Holy See (Vatican City State)"
      - "Saint Vincent and the Grenadines"
      - "Venezuela"
      - "Virgin Islands, British"
      - "Virgin Islands, U.s."
      - "Viet Nam"
      - "Vanuatu"
      - "Wallis and Futuna"
      - "Samoa"
      - "Yemen"
      - "Mayotte"
      - "South Africa"
      - "Zambia"
      - "Zimbabwe"
    allowMultiple: false

  ######################################################
  ########    OrangeHRM: Admin User Creation      ######
  ######################################################

  orangehrm_admin_firstname:
    type: string
    required: true
    title: First Name

  orangehrm_admin_lastname:
    type: string
    required: true
    title: Last Name

  orangehrm_admin_email:
    type: string
    required: true
    title: Email

  orangehrm_admin_contact_number:
    type: string
    required: false
    title: Contact Number

  orangehrm_admin_user_name:
    type: string
    required: true
    title: Admin Username

  orangehrm_admin_user_password:
    type: password
    required: true
    title: Password
    confirmation: true

  registration_consent:
    type: boolean
    required: true
    title: Register your system with OrangeHRM
    description: By registering, You will be eligible for free support via emails, receive security alerts and news letters from OrangeHRM.
    default: true

  ######################################################
  ##############    COMPUTE VARIABLES      #############
  ######################################################

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compute Compartment
    description: The compartment in which to create all Compute resources
    default: compartment_ocid

  tag_key_name:
    type: string
    required: true
    title: Tag key name

  tag_value:
    type: string
    required: true
    title: Tag value

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: false
    default: ""
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH

  vm_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the Instance

  vm_compute_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Compute Shape
    required: true
    dependsOn:
      compartmentId: compartment_ocid

  vm_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
            - eq:
                - vm_compute_shape
                - "VM.Standard3.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.E3.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.E4.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.A1.Flex"
            - eq:
                - vm_compute_shape
                - "VM.DenseIO.E4.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Optimized3.Flex"

  vm_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 64
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
            - eq:
                - vm_compute_shape
                - "VM.Standard3.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.E3.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.E4.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Standard.A1.Flex"
            - eq:
                - vm_compute_shape
                - "VM.DenseIO.E4.Flex"
            - eq:
                - vm_compute_shape
                - "VM.Optimized3.Flex"

  ######################################################
  ##############     NETWORK VARIABLES     #############
  ######################################################

  ######## VCN ########

  vcn_display_name:
    visible: true
    type: string
    required: true
    title: Name
    description: The name of the new Virtual Cloud Network (VCN)

  vcn_cidr_block:
    visible: true
    type: string
    required: true
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: CIDR Block
    description: The CIDR of the new Virtual Cloud Network (VCN). If you plan to peer this VCN with another VCN, the VCNs must not have overlapping CIDRs.
    default: "10.0.0.0/16"

  vcn_dns_label:
    visible: true
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: VCN DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

  ######## MANAGEMENT SUBNET ########
  subnet_display_name:
    visible: true
    type: string
    required: true
    title: Name
    description: The name of the new Subnet

  subnet_cidr_block:
    visible: true
    type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: CIDR Block
    description: The CIDR of the new Subnet. The new subnet's CIDR should not overlap with any other subnet CIDRs.
    default: "10.0.0.0/24"

  subnet_dns_label:
    visible: true
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: Subnet DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

  ######################################################
  ##############       MDS VARIABLES       #############
  ######################################################

  privileged_database_user_password:
    type: password
    required: false
    title: Privileged Database User Password
    minLenght: 8
    description: MySQL root user password

  privileged_database_username:
    type: string
    required: false
    title: Privileged Database Username
    description: "Privileged database user's username. e.g: root"

  database_name:
    type: string
    required: false
    title: Database name

  orangehrm_database_user_password:
    type: password
    required: false
    title: OrangeHRM Database User Password
    description: Database user password for the OrangeHRM application

  database_hostname:
    type: string
    required: false
    title: Database hostname
    description: Database hostname label within the subnet
  
  mysql_shape:
    type: string
    visible: false
    required: false
    default: "MySQL.VM.Standard.E3.1.8GB"
    title: MySQL Shape


#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Instance Management"
    outputs:
      - instance_public_ip
      - instance_private_ip

#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  instance_https_url:
    type: link
    title: Open Application URL
    visible: false

  instance_public_ip:
    type: link
    title: Public IP
    visible: true

  instance_private_ip:
    type: link
    title: Private IP
    visible: true

primaryOutputButton: instance_https_url
