title: Sample Marketplace Stack / ORM Application
description: This is a Sample Marketplace Stack / ORM Application
schemaVersion: 1.1.0
version: "20230127"

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - availability_domain_number

  - title: "Compute Configuration"
    variables:
      - compartment_ocid
      - vm_display_name
      - vm_compute_shape
      - vm_flex_shape_ocpus
      - vm_flex_shape_memory
      - availability_domain_name

  - title: "Virtual Cloud Network"
    variables:
      - vcn_display_name
      - vcn_dns_label
      - vcn_cidr_block

  - title: "Simple Subnet"
    visible: true
    variables:
      - subnet_display_name
      - subnet_dns_label
      - subnet_cidr_block

variables:
######################################################
##############    HIDDEN VARIABLES       #############
######################################################

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true
  
  availability_domain_number:
    type: string
    required: false
    description: Availability Domain Number (Not used)

######################################################
##############    COMPUTE VARIABLES      #############
######################################################

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compute Compartment
    description: The compartment in which to create all Compute resources
    default: compartment_ocid
  
  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  vm_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the Instance

  vm_compute_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Compute Shape
    required: true
    dependsOn:
      compartmentId: compartment_ocid
      #Comment in to restrict to marketplace image allowed shapes 
      #imageId: mp_listing_resource_id

  vm_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - vm_compute_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Optimized3.Flex"

  vm_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 64
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - vm_compute_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_compute_shape
            - "VM.Optimized3.Flex"

######################################################
##############     NETWORK VARIABLES     #############
######################################################

######## VCN ########

  vcn_display_name:
    visible: true
    type: string
    required: true
    title: Name
    description: The name of the new Virtual Cloud Network (VCN)

  vcn_cidr_block:
    visible: true
    type: string
    required: true
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: CIDR Block
    description: The CIDR of the new Virtual Cloud Network (VCN). If you plan to peer this VCN with another VCN, the VCNs must not have overlapping CIDRs.
    default: "10.0.0.0/16"

  vcn_dns_label:
    visible: true
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: VCN DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

######## MANAGEMENT SUBNET ########
  subnet_display_name:
    visible: true
    type: string
    required: true
    title: Name
    description: The name of the new Subnet

  subnet_cidr_block:
    visible: true
    type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: CIDR Block
    description: The CIDR of the new Subnet. The new subnet's CIDR should not overlap with any other subnet CIDRs.
    default: "10.0.0.0/24"

  subnet_dns_label:
    visible: true
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: Subnet DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Instance Management"
    outputs:
      - instance_public_ip
      - instance_private_ip


#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  instance_https_url:
    type: link
    title: Open Application URL
    visible: false

  instance_public_ip:
    type: link
    title: Public IP
    visible: #($mgmt_subnet_type == "Public Subnet")
      eq:
      - mgmt_subnet_type
      - "Public Subnet"

  instance_private_ip:
    type: link
    title: Private IP
    visible: true

primaryOutputButton: instance_https_url
